import type { ActivityItem, GithubRepository, MemberDetails, Organization, ProjectDetails } from './contracts';

export const mockActivity: ActivityItem[] = [
    {
        id: 'activity-yahub-update',
        type: 'repository_update',
        projectSlug: 'yahub',
        projectName: 'YAHub',
        description: 'Base inicial do portal e área administrativa em evolução.',
        author: 'Nícolas Machado Cardoso',
        occurredAt: '2026-07-04T18:00:00Z',
        referenceUrl: 'https://github.com/ya-labs/YA-HUB',
    },
    {
        id: 'activity-cade-o-dano',
        type: 'commit',
        projectSlug: 'cade-o-dano',
        projectName: 'CADE O DANO',
        description: 'Experimentos com API pública e experiência de estudo aplicada.',
        author: 'YA LABS',
        occurredAt: '2026-06-05T15:20:28Z',
        referenceUrl: 'https://github.com/ya-labs/CADE-O-DANO',
    },
    {
        id: 'activity-yabook-docs',
        type: 'repository_update',
        projectSlug: 'yabook',
        projectName: 'YABook',
        description: 'Atualização do método de trabalho e guias reutilizáveis da organização.',
        author: 'YA LABS',
        occurredAt: '2026-06-16T16:21:22Z',
        referenceUrl: 'https://github.com/ya-labs/YABook',
    },
];

export const mockProjects: ProjectDetails[] = [
    {
        id: 'yahub',
        slug: 'yahub',
        githubRepositoryId: 'ya-labs-yahub',
        githubOwner: 'ya-labs',
        githubName: 'YA-HUB',
        displayName: 'YAHub',
        tagline: 'Portal oficial da YA LABS.',
        category: 'produto',
        affiliation: 'oficial',
        shortDescription: 'Portal institucional para apresentar projetos, membros e atividades da YA LABS.',
        fullDescription: 'O YAHub centraliza a presença pública da YA LABS e prepara a base para integrações futuras.',
        status: 'desenvolvimento',
        visibility: 'publico',
        primaryLanguage: 'TypeScript',
        repositoryUrl: 'https://github.com/ya-labs/YA-HUB',
        websiteUrl: null,
        documentationUrl: null,
        technologies: ['React', 'TypeScript', 'Spring Boot'],
        updatedAt: '2026-07-04T18:00:00Z',
        featured: true,
        displayOrder: 1,
        yalabsMentorIds: [],
        responsibleMemberIds: ['nicolas'],
        recentActivities: mockActivity.filter((activity) => activity.projectSlug === 'yahub'),
    },
    {
        id: 'cade-o-dano',
        slug: 'cade-o-dano',
        githubRepositoryId: 'ya-labs-cade-o-dano',
        githubOwner: 'ya-labs',
        githubName: 'CADE-O-DANO',
        displayName: 'CADE O DANO',
        tagline: 'Estudo prático com APIs de jogos.',
        category: 'produto',
        affiliation: 'oficial',
        shortDescription: 'Projeto de estudo para testar integrações com APIs do League of Legends.',
        fullDescription:
            'Projeto público usado como laboratório de front-end, consumo de API e organização de produto.',
        status: 'desenvolvimento',
        visibility: 'publico',
        primaryLanguage: 'TypeScript',
        repositoryUrl: 'https://github.com/ya-labs/CADE-O-DANO',
        websiteUrl: null,
        documentationUrl: null,
        technologies: ['React', 'TypeScript'],
        updatedAt: '2026-06-05T15:20:28Z',
        featured: true,
        displayOrder: 2,
        yalabsMentorIds: [],
        responsibleMemberIds: ['nicolas'],
        recentActivities: mockActivity.filter((activity) => activity.projectSlug === 'cade-o-dano'),
    },
    {
        id: 'yabook',
        slug: 'yabook',
        githubRepositoryId: 'ya-labs-yabook',
        githubOwner: 'ya-labs',
        githubName: 'YABook',
        displayName: 'YABook',
        tagline: 'Método de trabalho e base de conhecimento da YA LABS.',
        category: 'ecossistema',
        affiliation: 'oficial',
        shortDescription: 'Documentação viva para processos, uso de IA, design system e condução de projetos.',
        fullDescription: 'O YABook concentra os padrões organizacionais reutilizáveis da YA LABS.',
        status: 'ativo',
        visibility: 'publico',
        primaryLanguage: 'Markdown',
        repositoryUrl: 'https://github.com/ya-labs/YABook',
        websiteUrl: null,
        documentationUrl: 'https://github.com/ya-labs/YABook/tree/main/docs',
        technologies: ['Markdown', 'GitHub'],
        updatedAt: '2026-06-16T16:21:22Z',
        featured: true,
        displayOrder: 3,
        yalabsMentorIds: [],
        responsibleMemberIds: ['nicolas'],
        recentActivities: mockActivity.filter((activity) => activity.projectSlug === 'yabook'),
    },
    {
        id: 'svnflow',
        slug: 'svnflow',
        githubRepositoryId: 'nicolasmacardoso-svnflow',
        githubOwner: 'nicolasmacardoso',
        githubName: 'SVNFlow',
        displayName: 'SVNFlow',
        tagline: 'Aplicativo desktop para apoiar fluxos com Git e SVN.',
        category: 'produto',
        affiliation: 'orientado',
        shortDescription: 'Projeto autoral acompanhado pela YA LABS em decisões de produto, documentação e interface.',
        fullDescription:
            'O SVNFlow é um projeto mantido pelo autor, com apoio pontual da YA LABS em organização, documentação e experiência de uso.',
        status: 'planejamento',
        visibility: 'publico',
        primaryLanguage: 'TypeScript',
        repositoryUrl: 'https://github.com/nicolasmacardoso/SVNFlow',
        websiteUrl: null,
        documentationUrl: null,
        technologies: ['TypeScript', 'Electron'],
        updatedAt: null,
        featured: true,
        authorDisplayName: 'Nícolas Machado Cardoso',
        supportTypes: ['mentoria', 'documentacao', 'revisao'],
        displayOrder: 4,
        yalabsMentorIds: ['nicolas'],
        responsibleMemberIds: ['nicolas'],
        recentActivities: [],
    },
];

export const mockGithubRepositories: GithubRepository[] = [
    {
        githubRepositoryId: 'ya-labs-yahub',
        githubOwner: 'ya-labs',
        githubName: 'YA-HUB',
        repositoryUrl: 'https://github.com/ya-labs/YA-HUB',
        primaryLanguage: 'TypeScript',
        technologies: ['React', 'TypeScript', 'Spring Boot'],
        description: 'Portal oficial da YA LABS.',
        topics: ['react', 'typescript', 'portal'],
        alreadyRegistered: true,
    },
    {
        githubRepositoryId: 'ya-labs-cade-o-dano',
        githubOwner: 'ya-labs',
        githubName: 'CADE-O-DANO',
        repositoryUrl: 'https://github.com/ya-labs/CADE-O-DANO',
        primaryLanguage: 'TypeScript',
        technologies: ['React', 'TypeScript'],
        description: 'Estudo prático com APIs de jogos.',
        topics: ['react', 'api', 'estudos'],
        alreadyRegistered: true,
    },
    {
        githubRepositoryId: 'ya-labs-yabook',
        githubOwner: 'ya-labs',
        githubName: 'YABook',
        repositoryUrl: 'https://github.com/ya-labs/YABook',
        primaryLanguage: 'Markdown',
        technologies: ['Markdown', 'GitHub'],
        description: 'Método de trabalho e base de conhecimento da YA LABS.',
        topics: ['documentacao', 'processos'],
        alreadyRegistered: true,
    },
    {
        githubRepositoryId: 'ya-labs-devlab',
        githubOwner: 'ya-labs',
        githubName: 'DevLab',
        repositoryUrl: 'https://github.com/ya-labs/DevLab',
        primaryLanguage: 'TypeScript',
        technologies: ['JavaScript', 'TypeScript'],
        description: 'Laboratório de estudos e práticas de desenvolvimento da YA LABS.',
        topics: ['estudos', 'javascript', 'typescript'],
        alreadyRegistered: false,
    },
];

export const mockMembers: MemberDetails[] = [
    {
        id: 'nicolas',
        slug: 'nicolas',
        name: 'Nícolas Machado Cardoso',
        role: 'Product / Front-end / UX',
        githubUsername: 'nicolasmacardoso',
        spotifolioUsername: null,
        responsibilities: ['Idealização do YAHub', 'Direção funcional', 'Front-end'],
        projectSlugs: ['yahub', 'cade-o-dano'],
        bio: 'Desenvolvedor full-stack em evolução, com foco em produtos reais, documentação e experiência de uso.',
        links: [{ label: 'GitHub', url: 'https://github.com/nicolasmacardoso' }],
    },
    {
        id: 'caio',
        slug: 'caio',
        name: 'Caio Matheus Queiroz',
        role: 'Back-end / API',
        githubUsername: 'cmathxus',
        spotifolioUsername: null,
        responsibilities: ['Back-end', 'Contratos de API', 'Tratamento de dados'],
        projectSlugs: ['yahub'],
        bio: null,
        links: [{ label: 'GitHub', url: 'https://github.com/cmathxus' }],
    },
];

export const mockOrganization: Organization = {
    name: 'YA LABS',
    description: 'Organização voltada a desenvolvimento de produtos, estudos técnicos e experimentos de software.',
    links: [{ label: 'GitHub', url: 'https://github.com/ya-labs' }],
    stats: {
        projects: mockProjects.length,
        members: mockMembers.length,
    },
    highlight: 'Projetos reais, documentação viva e evolução técnica compartilhada.',
};
