import type { ActivityItem, MemberDetails, Organization, ProjectDetails } from './contracts';

export const mockActivity: ActivityItem[] = [
    {
        id: 'activity-yahub-update',
        type: 'repository_update',
        projectSlug: 'yahub',
        projectName: 'YAHub',
        description: 'Base inicial do portal e área administrativa em evolução.',
        author: 'Nícolas Machado Cardoso',
        occurredAt: '2026-07-04T18:00:00Z',
        referenceUrl: 'https://github.com/ya-labs/YA-HUB',
    },
    {
        id: 'activity-cade-o-dano',
        type: 'commit',
        projectSlug: 'cade-o-dano',
        projectName: 'CADE O DANO',
        description: 'Experimentos com API pública e experiência de estudo aplicada.',
        author: 'YA LABS',
        occurredAt: '2026-06-05T15:20:28Z',
        referenceUrl: 'https://github.com/ya-labs/CADE-O-DANO',
    },
];

export const mockProjects: ProjectDetails[] = [
    {
        id: 'yahub',
        slug: 'yahub',
        githubRepositoryId: 'ya-labs-yahub',
        githubOwner: 'ya-labs',
        githubName: 'YA-HUB',
        displayName: 'YAHub',
        tagline: 'Portal oficial da YA LABS.',
        category: 'produto',
        affiliation: 'oficial',
        shortDescription: 'Portal institucional para apresentar projetos, membros e atividades da YA LABS.',
        fullDescription: 'O YAHub centraliza a presença pública da YA LABS e prepara a base para integrações futuras.',
        status: 'desenvolvimento',
        visibility: 'publico',
        primaryLanguage: 'TypeScript',
        repositoryUrl: 'https://github.com/ya-labs/YA-HUB',
        websiteUrl: null,
        documentationUrl: null,
        technologies: ['React', 'TypeScript', 'Spring Boot'],
        updatedAt: '2026-07-04T18:00:00Z',
        featured: true,
        displayOrder: 1,
        yalabsMentorIds: [],
        responsibleMemberIds: ['nicolas'],
        recentActivities: mockActivity.filter((activity) => activity.projectSlug === 'yahub'),
    },
    {
        id: 'cade-o-dano',
        slug: 'cade-o-dano',
        githubRepositoryId: 'ya-labs-cade-o-dano',
        githubOwner: 'ya-labs',
        githubName: 'CADE-O-DANO',
        displayName: 'CADE O DANO',
        tagline: 'Estudo prático com APIs de jogos.',
        category: 'produto',
        affiliation: 'oficial',
        shortDescription: 'Projeto de estudo para testar integrações com APIs do League of Legends.',
        fullDescription: 'Projeto público usado como laboratório de front-end, consumo de API e organização de produto.',
        status: 'desenvolvimento',
        visibility: 'publico',
        primaryLanguage: 'TypeScript',
        repositoryUrl: 'https://github.com/ya-labs/CADE-O-DANO',
        websiteUrl: null,
        documentationUrl: null,
        technologies: ['React', 'TypeScript'],
        updatedAt: '2026-06-05T15:20:28Z',
        featured: true,
        displayOrder: 2,
        yalabsMentorIds: [],
        responsibleMemberIds: ['nicolas'],
        recentActivities: mockActivity.filter((activity) => activity.projectSlug === 'cade-o-dano'),
    },
];

export const mockMembers: MemberDetails[] = [
    {
        id: 'nicolas',
        slug: 'nicolas',
        name: 'Nícolas Machado Cardoso',
        role: 'Product / Front-end / UX',
        githubUsername: 'nicolasmacardoso',
        spotifolioUsername: null,
        responsibilities: ['Idealização do YAHub', 'Direção funcional', 'Front-end'],
        projectSlugs: ['yahub', 'cade-o-dano'],
        bio: 'Desenvolvedor full-stack em evolução, com foco em produtos reais, documentação e experiência de uso.',
        links: [{ label: 'GitHub', url: 'https://github.com/nicolasmacardoso' }],
    },
    {
        id: 'caio',
        slug: 'caio',
        name: 'Caio Matheus Queiroz',
        role: 'Back-end / API',
        githubUsername: 'cmathxus',
        spotifolioUsername: null,
        responsibilities: ['Back-end', 'Contratos de API', 'Tratamento de dados'],
        projectSlugs: ['yahub'],
        bio: null,
        links: [{ label: 'GitHub', url: 'https://github.com/cmathxus' }],
    },
];

export const mockOrganization: Organization = {
    name: 'YA LABS',
    description: 'Organização voltada a desenvolvimento de produtos, estudos técnicos e experimentos de software.',
    links: [{ label: 'GitHub', url: 'https://github.com/ya-labs' }],
    stats: {
        projects: mockProjects.length,
        members: mockMembers.length,
    },
    highlight: 'Projetos reais, documentação viva e evolução técnica compartilhada.',
};
