spring.application.name=yahub-api

spring.datasource.url=jdbc:postgresql://localhost:5433/yahub
spring.datasource.username=yahub
spring.datasource.password=yahub

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000